configMapGenerator:
- name: example-redis-config
  namespace: kube-logging
  files:
  - redis-config
resources:
- redis-pod.yaml
- name: example-logstash-config
  namespace: kube-logging
  files: 
  - logstash.conf
  - logstash.yml
