apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: kube-logging
  labels:
    app: fluentd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  labels:
    app: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: kube-logging
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-logging
  labels: 
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostname: fluentd
      containers:
      - name: fluentd
#        image: fluent/fluentd-kubernetes-daemonset:v1-debian-forward
        image: pstambaugh14/fluentd-daemonset
        imagePullPolicy: Always
#        lifecycle:
#          postStart:
#            exec:
#              command: ["sh", "-c", "gem install fluent-plugin-redis-store"]
        env:
#          - name: FLUENT_REDIS_HOST
#            value: "redis.kube-logging.svc.cluster.local"
#          - name: FLUENT_REDIS_PORT
#            value: 6379  
#          - name:  FLUENT_FOWARD_HOST
#            value: "redis.kube-logging.svc.cluster.local"
#          - name:  FLUENT_FOWARD_PORT
#            value: "6379"
#      - name: fluentd
#        image: fluent/fluentd-kubernetes-daemonset:v1.4.2-debian-elasticsearch-1.1
#        image: fluent/fluentd-kubernetes-daemonset:v1.7.3-debian-elasticsearch7-1.0
#        image:       
#        lifecycle:
#          postStart:
#            exec:
#              command: ["sh", "-c", "gem install fluent-plugin-redis-store"]
#         command: ["sh", "-c", "fluent-gem install fluent-plugin-redis-store"]              
#        env:
#          - name: FLUENT_ELASTICSEARCH_HOST
#            value: "elasticsearch.kube-logging.svc.cluster.local"
#          - name: FLUENT_REDISSTORE_HOST
#            value: redis.kube-logging.svc.cluster.local
#          - name: FLUENT_ELASTICSEARCH_HOST
#            value: "redis.kube-logging.svc.cluster.local"
#          - name: FLUENT_REDISSTORE_PORT
#            value: 6379             
#            value: 172.17.0.8
#          - name: FLUENT_ELASTICSEARCH_PORT
#            value: "6379"
#          - name: FLUENT_ELASTICSEARCH_SCHEME
#            value: "http"
#          - name: FLUENT_ELASTICSEARCH_SCHEME
#            value: "json"          
          - name: FLUENTD_SYSTEMD_CONF
            value: disable
          - name: cluster.name
            value: k8s-logs
#          - name: node.name
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.name  
#          - name: FLUENT_ELASTICSEARCH_SED_DISABLE
#            value: "true"            
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          name: example-fluentd-config
          items:
          - key: fluent.conf
            path: fluent.conf
          - key: kubernetes.conf
            path: kubernetes.conf
          - key: prometheus.conf      
            path: prometheus.conf
          - key: systemd.conf   
            path: systemd.conf
