apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv-volume
  namespace: kube-logging
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/share/elasticsearch/data"
